Add release.sh script to make release process easier
ChistaDATA/cluster-secret-operator pull request #9
Opened 2023-02-17 19:08 UTC by jhonis

2023-12-11 16:19 UTC, biju-s commented on release.sh
> +git push origin main
Direct push to main branch is blocked

2023-12-12 11:40 UTC, biju-s requested changes

2023-12-12 11:40 UTC, biju-s commented on release.sh
> +git push origin main
Direct push to main branch is not allowed

2023-12-12 11:51 UTC, jhonis commented on release.sh
> +git push origin main
This is fixed, I'm using the same strategy as the release pipeline.

2023-12-12 14:21 UTC, biju-s approved these changes

2023-12-12 14:23 UTC, merged